version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: node:16.13.0
    steps:
      - checkout
      - run npm run test
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy-todo-api.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main

      - pull-and-build:
          filters:
            branches:
              only:
                - main
